lasers:
  - name: laser_405
    COM_port: COM7
    
mirrors:
  - name: mirror_1_VIS
    COM_port: COM8
    x_position: 0
    y_position: 0
    affine_matrix_path: ./copylot/assemblies/photom/demo/affine_T.yml